### PR TITLE
Use ThreadLocalRandom

### PR DESCRIPTION
**Pull request by picknchew**
This PR removes _most_ local instantiations of Random and replaces it with ThreadLocalRandom. This will improve performance and get rid of the _random_ Random instances that are scattered everywhere.

### CODE REVIEW

**Comment by mastercoms** [comment]
This is nice, thank you for your work. However, I'm not sure about replacing the world's random instance. Are there any downsides to the world's random generation possibly not sharing the same seed?

Also, just to make sure, did you replace any random instances with a specific seed?

**Comment by picknchew** [comment]
I purposely did not change the world generation side of things. Most random's that were changed did not have seeds set. However, a few of them I found was not useful.

**Comment by mastercoms** [comment]
Sorry for the confusion, when I said "world random generation", I didn't mean world generation, but rather the generation of random values within the GlowWorld class, previously generated by a single Random instance. Does it matter that these cases have no guarantee of sharing the same seed?

**Comment by picknchew** [comment]
From what I could tell, no. It does not matter. ThreadLocalRandom generates only 1 seed and it's shared across the thread.

**Review by aramperes — APPROVED** [review]
Reviewed and approved by @kamcio96

**Pull request merged**
