### PR TITLE
[WIP] replace static recipe with datapack

### PR DESCRIPTION
**Pull request by KisaragiEffective**
This PR do:
* Add script to generate all vanilla recipe except banner, reather armor tainting, fireworks
* Replace static recipe with data packs
* Close GlowstoneMC/1.13-board#6

This PR has to do:
* [x] Flower -> Dye recipe
* [ ] Code migrations

### CODE REVIEW

**Comment by mastercoms** [comment]
This should be merged into 1.13, not dev.

**Comment by KisaragiEffective** [comment]
updated.

**Comment by KisaragiEffective** [comment]
I'll close this cause broke something

**Comment by KisaragiEffective** [comment]
---> #1070

**Pull request closed without merging**
