### PR TITLE
Linkstone runtime support

### PR DESCRIPTION
**Pull request by aki-ks**
This PR redirects uses of fields annotated with a `@Field` annotation to the corresponding getter and setter methods. Regular invokes and reflective accesses will be redirected.

[Glowkit#20](https://github.com/GlowstoneMC/Glowkit/pull/20) must be merged for this PR.

### CODE REVIEW

**Comment by aki-ks** [comment]
[Linkstone#4](https://github.com/GlowstoneMC/Linkstone/pull/4/) must also be merged and the "annotation" and "runtime" submodules must be published onto a repository.

**Comment by WesleyVanNeck** [comment]
what is linkstone ?

**Comment by MatrixTunnel** [comment]
This explains it pretty well https://github.com/GlowstoneMC/Linkstone/blob/master/README.md

**Comment by mastercoms** [comment]
@aki-ks What is the status of this PR? Do you think it could be reviewed for merge in its current state?

**Comment by aki-ks** [comment]
Yes, I think so, but you must first make the `linkstone-runtime` and `linkstone-annotations` dependency available to the project (publish it on glowstone's maven repo).

**Comment by mastercoms** [comment]
This is currently blocked by Linkstone getting a working CircleCI build.

**Comment by mastercoms** [comment]
Linkstone is now deployed to our Maven repo, through GitHub Actions, so this PR is no longer blocked.

**Comment by mastercoms** [comment]
aki-ks has signed the CLA, but the bot does not recognize the slightly renamed username.

**Pull request merged**
