### PR TITLE
[WIP] Structure template API

### PR DESCRIPTION
**Pull request by aramperes**
This PR will add a completely new Structure API to Glowstone++. The aim of these changes is for custom structures and customizable generation by server owners and plugin developers to be possible. This will also mean that all current structures (Temples, Igloos, End City) will be converted into a JSON-based file structure, 'templates'.

This PR consists of:
- Converting hard-coded structures into loadable JSON file templates
- Runtime generation manipulation by plugins
- Geometric and Schematic structure support
  - Geometry can be used to create simpler structures with shapes
  - Schematics can be used by server owners (because it is a universal format)

Current development progress:
- [x] API for Structure templates
  - [x] Geometric structure builder
  - [ ] Schematic structure builder
- [ ] JSON file loader (templates)
- [ ] Add templates to world generation
- [ ] Document
- [ ] Testing

Sample Igloo template (WIP): https://gist.github.com/momothereal/afdc9f533e0559dc447b754b6c793a53

### CODE REVIEW

**Comment by Paulomart** [comment]
Will this also allow loading in mojang format?

**Comment by aramperes** [comment]
No, we decided to move away from Mojang stuff and unite structures into one format. Igloo and End City will be re-made using Geometry.

**Comment by Paulomart** [comment]
What about allowing to load mojang format? For faster updating, etc.

**Comment by aramperes** [comment]
We dont want to distribute the assets, though.

> mastercoms: You don't have to hard code them, but don't import the file from 1.9. I think that we should look at the information in them, and determine the best way to organize that information ourselves. If we want to use JSON, we shouldn't be changing formats just because we're copying code. We should make our own original structure for the JSON that can be better than the Mojang structure, and use the file format best suited for our purposes, not because we want to avoid being similar to Mojang.

**Comment by Paulomart** [comment]
ok then

**Comment by mastercoms** [comment]
What happened? :(

**Comment by aramperes** [comment]
@mastercoms Long story short, I tried squashing two commits and accidentally merged two branches together, so I'll need to re-commit the changes to this PR.

**Pull request closed without merging**
