### PR TITLE
Spongeapi

### PR DESCRIPTION
**Pull request by deathcap**
Based on @SpaceManiac's initial work in https://github.com/GlowstoneMC/ShinySponge

Current status: loads plugins in `plugins/` directory, sends init and disable events, not much else

Tested with plugin: https://github.com/deathcap/SampleSpongePlugin

```
20:34:22 [INFO] Loading Shiny...
20:34:22 [INFO] Glowstone git-Glowstone-"f894f69" is starting...
20:34:22 [INFO] SpongeAPI version: 1.8.3-R0.1-SNAPSHOT
20:34:22 [INFO] Loading plugins...
20:34:22 [INFO] SampleSpongePlugin preinitializing! net.glowstone.shiny.event.ShinyPreInitEvent@30c43f00
20:34:22 [INFO] Initializing plugins...
20:34:22 [INFO] SampleSpongePlugin preinitializing! net.glowstone.shiny.event.impl.PreInitializationEvent$Impl@7a0c1f5f
20:34:23 [INFO] Preparing spawn for world...
20:34:23 [INFO] Preparing spawn for world: done
20:34:23 [INFO] Preparing spawn for world_nether...
20:34:24 [INFO] Preparing spawn for world_nether: done
20:34:24 [INFO] Preparing spawn for world_the_end...
20:34:24 [INFO] Preparing spawn for world_the_end: done
20:34:24 [INFO] Ready for connections.
>stop
20:34:42 [INFO] CONSOLE: Stopping the server..
20:34:42 [INFO] The server is shutting down...
20:34:42 [INFO] SampleSpongePlugin disabling
```

Still to do:
- [x] Implement the ConfigurationLoader interface, must be important since the Sponge plugin archetype has it, albeit unused, commented-out for now: https://github.com/deathcap/SampleSpongePlugin/commit/b4b2879950c740f096c713dbece7b832573e55d8
- [x] Pass tests and build on CircleCI
- [x] Fix PreInitializationEvent being sent twice, something's clearly wrong there (different event?)
- [x] Decide how Bukkit API and Sponge API plugins are to coexist, in the same `plugins` directory (if can reliably differentiate) or separate? Currently the Bukkit loader barfs, but ignores the Sponge plugins:

```
20:34:22 [SEVERE] Could not load 'plugins/SampleSpongePlugin-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133)
    at net.glowstone.GlowServer.loadPlugins(GlowServer.java:705)
    at net.glowstone.GlowServer.start(GlowServer.java:451)
    at net.glowstone.GlowServer.main(GlowServer.java:108)
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
    ... 5 more
```

they can be differentiated by: Bukkit plugins have a plugin.yml, Sponge plugins have a @Plugin annotation
- [x] SpongeAPI BlockBreakEvent, posting and cancellation
- <s>Implement more events and interfaces</s> moved to https://github.com/deathcap/GlowstonePlusPlus/issues/45

### CODE REVIEW

**Comment by mastercoms** [comment]
Can Pore be used for this in some way? Or the reverse of it?

And I still think the best way to do this is by having a GlowBridge API.

**Comment by deathcap** [comment]
https://github.com/LapisBlue/Pore is an implementation of the Bukkit API on top of the Sponge API, so it could be used if Glowstone++ changed to be a Sponge API implementation. But to not regress from the current Bukkit API implementation, the Sponge API + implementation would have to be a superset of Bukkit, and Pore would have to be complete - seems a ways off, and would be giving up Glowstone's key advantage as a Bukkit API server. 

The opposite, a Sponge API implementation on top of the Bukkit API, would be interesting to help with the transition - especially if it could allow running Sponge plugins on Glowstone, Spigot, and other Bukkit API implementations.

What do you mean by GlowBridge?

**Comment by deathcap** [comment]
Not sure what's going on with the failing CircleCI tests, something with SpongeAPI dependency, but the Codeship CI test passes:

Downloading: https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/1.1-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/spongepowered/spongeapi/1.1-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/public/org/spongepowered/spongeapi/1.1-SNAPSHOT/maven-metadata.xml



[WARNING] Could not transfer metadata org.spongepowered:spongeapi:1.1-SNAPSHOT/maven-metadata.xml from/to sponge-repo (https://repo.spongepowered.org/maven): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.spongepowered:spongeapi:1.1-SNAPSHOT/maven-metadata.xml from https://repo.spongepowered.org/maven was cached in the local repository, resolution will not be reattempted until the update interval of sponge-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.spongepowered:spongeapi:1.1-SNAPSHOT/maven-metadata.xml from/to sponge-repo (https://repo.spongepowered.org/maven): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Added ConfigurationLoader support so the sample plugin loads unmodified.

For the Bukkit/Sponge plugins directory, I'm thinking should first try to load as Sponge (which scans the classes for a @Plugin annotation), if it finds plugin(s), load, otherwise add to list of not-loaded plugins and let the Bukkit API have a chance at loading. This way both plugin types should be able to seamlessly coexist in the same directory. If a plugin jar contains both Sponge and Bukkit (possible? anyone do this?), then Sponge will be preferred.

**Comment by mastercoms** [comment]
GlowBridge would be like Sunflower. We import GlowBridge classes and we use GlowBridge methods, which return either Bukkit or Sponge methods.

**Comment by deathcap** [comment]
This is about ready to merge; SpongeAPI plugins load, are skipped from Bukkit, and receive a few events:

- [x] ConstructionEvent
- [x] PreInitializationEvent
- [x] ServerStoppingEvent
- [x] BlockBreakEvent

Tested with https://github.com/deathcap/SampleSpongePlugin (logs init/disable, and block break events, includes a simple test for event cancellation preventing block breakage). Sunflower/GlowBridge can be discussed in https://github.com/deathcap/GlowstonePlusPlus/issues/14. More events can be added with time, there's obviously tons missing, but this is at least a start.

**Pull request merged**
