### PR TITLE
Change to use Spigot API for particle effects

### PR DESCRIPTION
**Pull request by deathcap**
Glowkit added a particle API under org.bukkit.Particle in https://github.com/GlowstoneMC/Glowkit/pull/22, separate from Spigot's API: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0006-Add-Particle-API.patch . The main difference is that Spigot extends org.bukkit.Effect, also used for other kinds of effects, instead of adding org.bukkit.Particle as in Glowkit. This is currently an API addition added by Spigot in Bukkit-Patches, not part of their regular Bukkit API update. Older patch also available in Spigot-API: https://github.com/SpigotMC/Spigot-API/commit/39222517a326474e4d198c4811094b1750bf71f6 (but since moved to SpigotMC's stash). 

Part of https://github.com/deathcap/GlowstonePlusPlus/issues/5 Investigate supporting Spigot API
additions (Bukkit-Patches)

---

Requires API change: https://github.com/deathcap/Glowkit/pull/1

This PR is not ready to pull, there are several major issues making it incomplete. Worse, there are discrepancies between various reference sources. In particular:
- Protocol documentation http://wiki.vg/Protocol#Effect lists particle names and particle IDs, 0 to 35. But is missing 36 to 41: Glowkit enum names: 

```
+        set(ITEM_BREAK, 36);
+        set(BLOCK_BREAK, 37);
+        set(BLOCK_DUST, 38);
+        set(WATER_DROPLET, 39);
+        set(ITEM_TAKE, 40);
+        set(MOB_APPEARANCE, 41);
```
- [Spigot API](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0006-Add-Particle-API.patch) includes string names and API enum values, but no IDs. Seems to be missing some particles - where is "barrier" (35), for example?
- [GlowstoneMC implementation](https://github.com/GlowstoneMC/Glowstone/commit/042330d3ffee5ae4ea239c2b63f0be7e36e7aaa1#diff-04c5b20f291f16a0c63ccd9e60a28d4fR77) includes Glowkit enum values to numeric IDs, but might have an error: `set(VOID_FOG, 8); // depth suspend`, but wiki.vg assigns id 8 to "townaura", and "depthsuspend" is 22 (Spigot enum name `VOID_FOG`).

first need to reconcile these differences, comprehensively map the string names to numeric IDs, then add missing enum values to the API, finish converting Glowstone++ to the new API, and test

### CODE REVIEW

**Comment by mastercoms** [comment]
The best thing we can do is maintain compatibility with Spigot, then add extra effects that spigot does not have.

**Comment by deathcap** [comment]
Particles have to have numeric IDs since that is what is sent in the 0x2a packet int field. But the wiki.vg documentation had a bunch of errors. MinecraftWiki's list is comprehensive:

http://minecraft.gamepedia.com/Particles

(and even includes screenshots). They don't list the IDs, but they are in numerical order from 0 explode up to 35 barrier, then the order diverges (for the new particles which weren't in Spigot API either). But it does have all of the particle names. There are plugin APIs also listing all particles:

http://www.spigotmc.org/resources/lib-particlelib-1-7-1-8.2067/ - after BARRIER (35) is, in order:

36 ITEM_CRACK
37 BLOCK_CRACK
38 BLOCK_DUST
39 WATER_DROP
40 ITEM_TAKE
41 MOB_APPEARANCE

more APIs/documentation:

* http://www.inventivegames.de/javadoc/ParticleLIB/
* https://bukkit.org/threads/particle-packet-library.138493/
* https://bukkit.org/threads/1-8-customized-colored-particles-rgb.332949/
* http://www.spigotmc.org/resources/trailgui.1091/

The original Minecraft server also has a command to spawn particles:

```
Usage: /particle <name> <x> <y> <z> <xd> <yd> <zd> <speed> [count] [mode]
```

which can be cross-referenced with the ID field in the 0x2a packet.

Updated the list at http://wiki.vg/Protocol#Particle  - think it is 100% correct now

**Comment by deathcap** [comment]
Test plugin: https://gist.github.com/deathcap/03fbcc7be391b539c65a

**Comment by mastercoms** [comment]
So what is the item_take particle?

**Comment by mastercoms** [comment]
Ah, I see. I guess it's more efficient to send an int rather than a string :laughing:

**Pull request merged**
