### PR TITLE
Fix grammar and outdated information in README

### PR DESCRIPTION
**Pull request by colinmcmillen**
I made some fixes to the grammar issues I found and updated the outdated information and links.

### CODE REVIEW

**Review by aramperes — APPROVED** [review]

**Comment by colinmcmillen** [comment]
Could you please merge this?

**Comment by gdude2002** [comment]
Momo (as the reviewer) can't, but I can

**Comment by colinmcmillen** [comment]
Thanks!

**Comment by mastercoms** [comment]
I posthumously approve this pr

**Comment by ethsmith** [comment]
Doesn't that mean after the death of the original, did gdude die? xD

**Comment by gdude2002** [comment]
posthumous is after _you_ died

**Comment by gdude2002** [comment]
Also, enough spam, dammit. Go to Discord for that. :P

**Comment by mastercoms** [comment]
after the pr died

don't worry I'm not dead

**Pull request merged**
