### PR TITLE
Add relocations for internal dependencies. Closes GH-190

### PR DESCRIPTION
**Pull request by deathcap**
Add relocations for internal dependencies. Closes GH-190

### CODE REVIEW

**Comment by deathcap** [comment]
Are there other dependencies which should be relocated similarly? Not libraries intended for plugin use (part of Bukkit API). Maybe asm and jline too?

**Comment by mastercoms** [comment]
I think asm and jline should be relocated as well.

**Comment by kamcio96** [comment]
Nooo, nothing should be reloacated (or only flownetworking). If plugin use custom lib, it should include that lib.

**Comment by Paulomart** [comment]
@kamcio96 but if a plugins the server to have netty 4, but it has netty 5?

**Comment by kamcio96** [comment]
so plugin has to include netty 4

**Comment by Paulomart** [comment]
Still it's an issue with custom injection, see my ticket.

**Comment by kamcio96** [comment]
I wrote, here is bug: https://github.com/GlowstonePlusPlus/Glowkit/blob/bukkit%2Bglowkit/src/main/java/org/bukkit/plugin/java/PluginClassLoader.java#L97
:stuck_out_tongue_winking_eye:

**Comment by Paulomart** [comment]
But if we relocate Netty and flow it wouldn't be an issue for anyone, the plugin needs to have it itself.

**Comment by Paulomart** [comment]
I know but this way class lookups are faster because most of the classes are in the global class loader (I think?)

**Comment by kamcio96** [comment]
It is really small difference

**Comment by Paulomart** [comment]
Okey, but even then I don't see your issue with relocating

**Comment by kamcio96** [comment]
There is no issue, ofc we can relocate it like CraftBukkit 1.7.10 (in 1.8 md_5 drop that idea and use raw package). It is only my opinion. I don't like upload plugin update's with more 2Mb.

But still, class in glowkit should be changed.

**Comment by Paulomart** [comment]
You are saying that you don't like to upload big plugin files, but also saying that if a plugin is using netty, for example, it should be shaded in the plugin. This doesn't makes sense to me, sorry. The plugin would have to include it either way it you would want to make it right. Then there wore no problems with versions.

**Comment by mastercoms** [comment]
Let's add a lib API? So plugins can request for a library to be downloaded.

**Comment by Paulomart** [comment]
It's a very good, ideas, but then there must be support for custom sources, loading the plugin main without libs from that plugin and so on. I think this would be over engineered. Also there must be support for this in spigot too, otherwise people will just keep shading

**Pull request merged**
