### PR TITLE
Implement effect command

### PR DESCRIPTION
**Pull request by notourist**
This adds the /effect command (see #499 ).

### CODE REVIEW

**Comment by aramperes** [comment]
Would be nice to add tab-completion to this, like we did with the other commands.

**Comment by notourist** [comment]
I just checked the auto completion in vanilla Minecraft and all the effect names have a "minecraft:"-prefix. Should I leave this in or not, because currently the prefix gets removed.

**Comment by aramperes** [comment]
I think we should leave it in.

This is what we did for the `/give` command:

https://github.com/GlowstoneMC/Glowstone/blob/09e8432fab1f18a377560f0035221c435dd4a842/src/main/java/net/glowstone/command/minecraft/GiveCommand.java#L95-L100

However, I see that you are getting the potion IDs using the enum values (`Impl.values()`). So basically, you would add a new field to this enum (e.g. `key`) with the actual vanilla ID, with the namespace (e.g. `minecraft:regeneration`). Then you can map the potion effects using these IDs instead.

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you so much for your contribution!

**Pull request merged**
