### PR TITLE
Add missing MetadataIndexes and MetadataTypes.

### PR DESCRIPTION
**Pull request by Paulomart**
Based on http://wiki.vg/Entities

### CODE REVIEW

**Comment by Paulomart** [comment]
`Index ARMORSTAND_LEFT_LEG_POSITION(ArmorStand) conflicts with NO_AI(LivingEntity)` Ehrrr, blame Mojang for this one..

**Comment by kamcio96** [comment]
Add here https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/test/java/net/glowstone/entity/MetadataIndexTest.java#L50

**Comment by mastercoms** [comment]
Why can other metadata have the same index and not conflict?

**Comment by Paulomart** [comment]
Because they are other Entity, it checks the hierarchy

**Comment by mastercoms** [comment]
Ok, looks good to me.

**Pull request merged**
