### PR TITLE
Refactor 4 Message classes to take Location constructor param

### PR DESCRIPTION
**Pull request by Pr0methean**
New constructor overloads accept a Location parameter, eliminating lots of duplicate code to extract x,y,z,pitch,yaw. Also, methods returning only one instance of one or both classes now use Collections.singletonList.

### CODE REVIEW

**Comment by Pr0methean** [comment]
This also removes unused imports in net.glowstone.entity, even if they are pre-existing.

**Comment by mastercoms** [comment]
The collection returned by `Collections#singletonList` is immutable. I don't think we want that behavior.

**Comment by Pr0methean** [comment]
Many of the existing invocations return Arrays.asList(), which can't be resized, anyway.

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you for your one of many contributions to Glowstone! I've invited you to our organization, as per our [contributing policy](https://github.com/GlowstoneMC/Glowstone/blob/dev/.github/CONTRIBUTING.md).

**Comment by Pr0methean** [comment]
@mastercoms Thanks! For now I'll still wait a while for reviews when I'm making significant functional changes, but not for the remaining CheckStyle fixes (except where the former and the latter turn out to overlap, e.g. #633 ).

**Pull request merged**
