### PR TITLE
Adds support for basic dispenser actions

### PR DESCRIPTION
**Pull request by xxmicloxx**
This PR adds support for basic dispenser actions, while trying to imitate the notchian server as much as possible. Dispensers react exactly like on a vanilla server.
This PR does not only add dispensing items out of a dispenser, but also adds support for placing buckets, picking up buckets, placing TNT and lighting things on fire.

### CODE REVIEW

**Comment by mastercoms** [comment]
I've done a skimming of the code and it looks good so far, I'll review it more heavily during the weekend, and then test it if I don't find any problems. Hopefully I'll merge it after that.

Thanks for your contribution!

**Comment by mastercoms** [comment]
This PR breaks droppers. However, they didn't work anyway, so I'll let you decide if I should merge this PR, even with this regression.

https://gist.github.com/mastercoms/17b35a678ea8cdae7e62

**Comment by xxmicloxx** [comment]
I added a bugfix which, according to my testing, fixes the bug with droppers. They still act like dispensers, but they don't crash anymore.

**Comment by mastercoms** [comment]
Awesome. I will test it as soon as possible.

**Comment by mastercoms** [comment]
Ok, everything seems good.

**Comment by mastercoms** [comment]
I'm adding you to our project, as per our [Contribution Policy](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/CONTRIBUTING.md)

**Pull request merged**
