### PR TITLE
Fix CheckStyle issues in entity/passive/GlowVillager.java

### PR DESCRIPTION
**Pull request by Pr0methean**

### CODE REVIEW

**Comment by liach** [comment]
These checkstyles are blowing out my notifications lol

**Comment by Pr0methean** [comment]
@liach Don't worry, there won't be more than a handful after today.

**Comment by liach** [comment]
Why do you always have 4 commits?

**Comment by Pr0methean** [comment]
These are automatically branched from my device branch before files are cherry-picked over from my stylesquashed branch. My device branch has 3 branches at head. If this is still going when I get home, I'll rebase my dev and any further PRs will be one commit.

**Comment by liach** [comment]
eh, ok... bot fixing

**Pull request merged**
