### PR TITLE
Fix checkstyle violations

### PR DESCRIPTION
**Pull request by plexus**
So the build is no longer red.

### CODE REVIEW

**Comment by mastercoms** [comment]
The checkstyle rules should be upgraded instead, so that this code which conforms to our style passes checkstyle.

**Review by mastercoms — CHANGES_REQUESTED** [review]
Alright, I investigated further and fixed the brace rule. However, the import spacing rule is apparently intended, since the checkstyle was intended to enforce no spaces between groups. I guess we will have to roll with it for now, as any changes to the import order rules is going to cause much more breakage (1000 files) instead of this relatively small fix.

So, could you please revert the brace changes, and then I'll merge the import changes. Thanks for contributing!

**Comment by plexus** [comment]
I undid the brace changes and rebased. Thanks!

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you for your contribution to Glowstone!

**Pull request merged**
