### PR TITLE
Add metrics

### PR DESCRIPTION
**Pull request by kamcio96**
http://mcstats.org/plugin/GlowstonePlusPlus

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
Should be optional in the configuration in my opinion.

**Comment by kamcio96** [comment]
plugins\PluginMetrics\config.yml

**Comment by mastercoms** [comment]
Isn't it the plugins job to report metrics info about the server?

**Comment by kamcio96** [comment]
Plugins only report server's name. There we can see more info about it.

Spigot has http://mcstats.org/plugin/Spigot

**Comment by mastercoms** [comment]
Ah, ok.

**Pull request merged**
