### PR TITLE
Add cache to GlowBlock

### PR DESCRIPTION
**Pull request by kamcio96**
Fix some bugs with storage of block instance in plugins.

Eg:

``` java
Location loc = new Location(...)
Block b1 = loc.getBlock();
Block b2 = loc.getBlock();

b2.getType(); // return Material.ONE

b1.setType(Material.SOMEOTHER);
Material m = b2.getType(); // still return Material.ONE
```

### CODE REVIEW

**Comment by mastercoms** [comment]
Are you sure the bug you mentioned still occurs?
Output:

```
23:31:35 [INFO] [GlowTest] Original material: GRASS
23:31:35 [INFO] [GlowTest] Original material (id): 2
23:31:35 [INFO] [GlowTest] Original material (material from id): GRASS
23:31:35 [INFO] [GlowTest] Changed to Material.BEACON/138 using setType(Material)
23:31:35 [INFO] [GlowTest] Resultant material: BEACON
23:31:35 [INFO] [GlowTest] Resultant material (id): 138
23:31:35 [INFO] [GlowTest] Resultant material (material from id): BEACON
23:31:35 [INFO] [GlowTest] Changed to Material.NETHERRACK/97 using setType(Material, true)
23:31:35 [INFO] [GlowTest] Resultant material: NETHERRACK
23:31:35 [INFO] [GlowTest] Resultant material (id): 87
23:31:35 [INFO] [GlowTest] Resultant material (material from id): NETHERRACK
23:31:35 [INFO] [GlowTest] Changed to Material.DIRT/3 using setTypeId(int)
23:31:35 [INFO] [GlowTest] Resultant material: DIRT
23:31:35 [INFO] [GlowTest] Resultant material (id): 3
23:31:35 [INFO] [GlowTest] Resultant material (material from id): DIRT
23:31:35 [INFO] [GlowTest] Changed to Material.STONE/1 using setTypeId(int, true)
23:31:35 [INFO] [GlowTest] Resultant material: STONE
23:31:35 [INFO] [GlowTest] Resultant material (id): 1
23:31:35 [INFO] [GlowTest] Resultant material (material from id): STONE
23:31:35 [INFO] [GlowTest] Changed to Material.GLOWSTONE/89 using setTypeIdAndData(int, byte, true)
23:31:35 [INFO] [GlowTest] Resultant material: GLOWSTONE
23:31:35 [INFO] [GlowTest] Resultant material (id): 89
23:31:35 [INFO] [GlowTest] Resultant material (material from id): GLOWSTONE
```

Code:

``` java
    @EventHandler
    public void onPlayerInteractEvent(PlayerInteractEvent event) {
        Block block = event.getClickedBlock();
        getLogger().info("Original material: " + block.getType());
        getLogger().info("Original material (id): " + block.getTypeId());
        getLogger().info("Original material (material from id): " + Material.getMaterial(block.getTypeId()));
        getLogger().info("Changed to Material.BEACON/138 using setType(Material)");
        block.setType(Material.BEACON);
        getLogger().info("Resultant material: " + block.getType());
        getLogger().info("Resultant material (id): " + block.getTypeId());
        getLogger().info("Resultant material (material from id): " + Material.getMaterial(block.getTypeId()));
        getLogger().info("Changed to Material.NETHERRACK/97 using setType(Material, true)");
        block.setType(Material.NETHERRACK, true);
        getLogger().info("Resultant material: " + block.getType());
        getLogger().info("Resultant material (id): " + block.getTypeId());
        getLogger().info("Resultant material (material from id): " + Material.getMaterial(block.getTypeId()));
        getLogger().info("Changed to Material.DIRT/3 using setTypeId(int)");
        block.setTypeId(3);
        getLogger().info("Resultant material: " + block.getType());
        getLogger().info("Resultant material (id): " + block.getTypeId());
        getLogger().info("Resultant material (material from id): " + Material.getMaterial(block.getTypeId()));
        getLogger().info("Changed to Material.STONE/1 using setTypeId(int, true)");
        block.setTypeId(1, true);
        getLogger().info("Resultant material: " + block.getType());
        getLogger().info("Resultant material (id): " + block.getTypeId());
        getLogger().info("Resultant material (material from id): " + Material.getMaterial(block.getTypeId()));
        getLogger().info("Changed to Material.GLOWSTONE/89 using setTypeIdAndData(int, byte, true)");
        block.setTypeIdAndData(89, (byte) 0, true);
        getLogger().info("Resultant material: " + block.getType());
        getLogger().info("Resultant material (id): " + block.getTypeId());
        getLogger().info("Resultant material (material from id): " + Material.getMaterial(block.getTypeId()));
    }
```

As of https://github.com/GlowstoneMC/Glowstone/commit/85e98f311f766f18debf17c0ab649b964b60518e

**Comment by kamcio96** [comment]
You're using same `Block` instance

**Comment by mastercoms** [comment]
ok

**Comment by aramperes** [comment]
This Pull Request seems to greatly affect performance, it both generation times and overall functionality. I'm no performance expert myself, but this should be looked into.

**Comment by mastercoms** [comment]
affect as in negative or positive?

**Comment by aramperes** [comment]
Pretty negative. Destroying a block takes a second to register, and world generation is 5x longer.

**Comment by mastercoms** [comment]
I am not seeing those kinds of delays, but I am hitting 50% cpu usage and 2gb ram usage when placing blocks repeatedly.

**Comment by aramperes** [comment]
World generation is very slow. I've generated a couple worlds, with all similar results to these:

**World generation time with this PR**: 1 minute 55 seconds (115 seconds) ([log](http://hastebin.com/vorotecejo.tex))
**World generation with latest build**: 12 seconds ([log](http://hastebin.com/iwenozemem.tex))

I've not been able to reproduce that block lag I used to have, must have been caused by another factor.

**Comment by kamcio96** [comment]
I just realized, I did it wrong. 

Values have to be weak... 

WeakHashMap has weak keys. I can't close it now (android app). Can sb do it?

**Pull request closed without merging**
