### PR TITLE
Use upstream flow-network

### PR DESCRIPTION
**Pull request by twizmwazin**
The fork seems kinds pointless, it provides a _slightly_ upgraded version of netty, but no significant improvement. From my perspective, fewer forks makes the project easier to manage. This sorta goes along with my ideas from #221.

### CODE REVIEW

**Comment by Paulomart** [comment]
I'm so sorry github mobile sucks. 

Anyway yes you are right, when we used 5.x it made sense but we are no longer so this is good.

**Comment by MeltedLux** [comment]
CircleCI build fails because of this: https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/master/setup.sh#L4

**Comment by kamcio96** [comment]
(y)

**Comment by twizmwazin** [comment]
Dammit I thought I removed that, one sec

**Comment by mastercoms** [comment]
There are many significant improvements in Netty 4.1 and more are being added from Netty 5.0. I believe Netty 4.1 has more changes than 5.0 now. I would like more justification about downgrading than just because it is cleaner. I will pull request the other changes that we have to their repo.

**Comment by twizmwazin** [comment]
I'll be honest, I'm not sure why you need Netty 4.1, Netty 4.1 features were not used in g++ at all.

**Comment by mastercoms** [comment]
Some benefits are not new APIs and rather improvements to Netty itself. As with Java 8, I will port everything over to use newer features, but that will happen with time.

**Comment by twizmwazin** [comment]
But are these improvements actually significant to the project? What exactly are these improvements?

**Comment by mastercoms** [comment]
https://github.com/netty/netty/wiki/New-and-noteworthy-in-4.1

**Comment by mastercoms** [comment]
I don't think this will be merged.

**Pull request closed without merging**
