### PR TITLE
Ignoring inventory destroy item slot

### PR DESCRIPTION
**Pull request by ghost**
Ignoring inventory slot 45 (Destroy Item)
It throws a exception like this one:

```
java.lang.IllegalArgumentException: Slot out of range [0,45): 45
    at net.glowstone.inventory.GlowInventoryView.checkSlot(GlowInventoryView.java:86)
    at net.glowstone.inventory.GlowInventoryView.getItem(GlowInventoryView.java:71)
    at net.glowstone.net.handler.play.inv.CreativeItemHandler.handle(CreativeItemHandler.java:58)
    at net.glowstone.net.handler.play.inv.CreativeItemHandler.handle(CreativeItemHandler.java:20)
    at net.glowstone.libs.com.flowpowered.network.session.BasicSession.handleMessage(BasicSession.java:80)
    at net.glowstone.libs.com.flowpowered.network.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:462)
    at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:144)
    at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

### CODE REVIEW

**Comment by ethsmith** [comment]
Did you test this.. ?

**Comment by ghost** [comment]
Yeah

**Comment by ethsmith** [comment]
ok.

**Comment by aramperes** [comment]
So far, everything works with the Destroy Item button, but I am still having an issue with this;

For some reason, slot 45 also represents the Off-Hand slot. If you test clicking on the off-hand slot (the 'shield') with an item previously, it would throw an error (not exactly the same), but now it 'works', being that the item is duplicated to the slot 0.

Also, I would also recommend branching out master on your fork when doing changes, that way you can re-branch off master when you work on something else, while not having the changes of the previous branch.

**Pull request closed without merging**
