### PR TITLE
Pistons face the proper direction when placed.

### PR DESCRIPTION
**Pull request by aramperes**
Pistons will face the proper direction in regards of the player's location proportional to the block. This attempts to reproduce Vanilla behavior of piston placement.

_This has nothing to do with the functionality of pistons, yet...!_

### CODE REVIEW

**Comment by liach** [comment]
Because of your email address in commit?

**Comment by MOMOTHEREAL** [comment]
No, I accidentally pushed a merge in my master branch... and I don't really know what to do know (it should not be in the PR)... :S *help?*

**Comment by mastercoms** [comment]
Use git-rebase to make your branch fork off the right master commit.

**Comment by MOMOTHEREAL** [comment]
Right, now I have the latest commits from here, but I still have this commit laying around: https://github.com/MOMOTHEREAL/GlowstonePlusPlus/commit/5b6bff8cd8dbe0e31ed5a6ffe66c9bc214260f0b

How can I remove it? I have tried to do `git rebase -i HEAD~2` to remove it locally but the commit, but that certain commit is not shown on the list.

**Comment by mastercoms** [comment]
[I would just restart your repo.](https://xkcd.com/1597/)

**Comment by codekilla747** [comment]
THANK YOU! I noticed this in game and was so aggrevated with it.

**Pull request closed without merging**
