### PR TITLE
makes it possible to run a GlowServer as part of another application

### PR DESCRIPTION
**Pull request by jlirochon**
Example of minimal external application :

``` java
package com.acme;

import net.glowstone.GlowServer;

public class AcmeApplication {
    public static void main(String[] args) {
        GlowServer server = GlowServer.createFromArguments(args);

        // we don't want to run a server when called with --version
        if (server == null) {
            return;
        }

        // we could set some additional properties here

        try {
            glowServer.run();
        } catch (BindException e) {
            e.printStackTrace();
        }
    }
}
```

### CODE REVIEW

**Comment by jlirochon** [comment]
Please let me know if such a pull request would be acceptable, or if I can do anything to make it more pleasant :)

**Comment by mastercoms** [comment]
I don't think this is a patch suitable for Glowstone++, as it is intended to be its own server software. This patch should be for projects that need it.

**Comment by twizmwazin** [comment]
I don't see how this is a bad patch. This makes sense- make it easier for users to embed a server in their application, without changing normal functionality.

**Comment by jlirochon** [comment]
It could be used as part of your test suite too. For exemple a test class could run a GlowServer to check that the server is listening on tcp port, and replying to some basic commands like "help". This is called smoke testing.

**Comment by jlirochon** [comment]
Open source software often find many use cases that were not intended or expected. I don't see the point of intentionally making it difficult to use by third parties.

**Comment by jimmikaelkael** [comment]
I think this could be useful.

**Comment by mastercoms** [comment]
I guess since it doesn't affect us, we can merge it.

**Comment by jlirochon** [comment]
Thank you @twizmwazin @jimmikaelkael @mastercoms :)

**Pull request merged**
