### PR TITLE
Update protocol.

### PR DESCRIPTION
**Pull request by ghost**
Update to 17w06a.

### CODE REVIEW

**Comment by DaMatrix** [comment]
Have you actually tried joining with this? Simply changing the version number isn't enough for a big update like 1.12.

**Comment by ghost** [comment]
This is just the beginning, because the branch is called the "1.12-snapshots".

**Comment by gdude2002** [comment]
Honestly, this is such a trivial change that it does not need a pull request. I'm relatively confident that someone is already working on updating this branch, and they likely have already edited this file locally (and perhaps made this exact change), so accepting this PR would create annoying merge conflicts for them.

There's an awful lot of work to do, and this is definitely far too trivial for any serious PR.

---

On those grounds, I'm going to close this PR. While we appreciate any and all interest in our project, life is too short for two-line PRs.

**Comment by gdude2002** [comment]
Small edits like this belong in issues, but please be patient enough to allow us time to work on the branch first.

**Comment by mastercoms** [comment]
Hello and thank you for your interest in contributing to Glowstone! Since someone else is already working on this branch, @momothereal, I think it would be great if you could talk with him if you want to help make the 1.12 snapshots branch.

**Comment by aramperes** [comment]
I'm in Cambodia at the moment with very little free time. I still follow updates but I probably won't develop the branch actively for the coming weeks.

In my opinion, since there have been no protocol changes yet, we should focus on updating Glowkit to an experimental snapshot version for 1.12 first.

**Pull request closed without merging**
