### PR TITLE
tweak nether soulsand and gravel gen

### PR DESCRIPTION
**Pull request by mastercoms**
This pull request has been opened to have open discourse about height values and frequency of soul sand and gravel generation in the nether.

### CODE REVIEW

**Comment by deathcap** [comment]
Hows this compare to the official Minecraft server?

**Comment by mastercoms** [comment]
I have no idea, the values I put are not exact at all. Just made an issue to discuss what values would be vanilla like.

**Comment by mastercoms** [comment]
So can we agree on some default values?

**Comment by mastercoms** [comment]
I'm doing a rewrite of the world manager and I'll come back to this during that.

**Pull request closed without merging**
