### PR TITLE
Lightning damage and ignites

### PR DESCRIPTION
**Pull request by jimmikaelkael**
Enhancement of Glowstone PR  #637.

I have enhanced in several way as to respect vanilla behavior: 
- the lightning bolt can retarget on nearby living entities
- it checks the targeted block is receiving rain
- it can set a few flammable blocks on fire
- prevents creative or spectator players to receive damage or to be set on fire

### CODE REVIEW

**Comment by jimmikaelkael** [comment]
I kept almost nothing from the original PR, but now it matches the wiki: http://minecraft.gamepedia.com/Thunderstorm
I still need to set a few blocks on fire.

I'm currently facing a problem with damages: I receive damages even if I'm in creative mode, and I'm almost sure something is missing like an override of the canTakeDamage method in GlowPlayer to ensure the player is not in creative or spectator mode. Any tought about this ?

I find currently strange to check for creative mode everytime we want to call damage, especially when you're working with LivingEntity and not Player.

**Comment by mastercoms** [comment]
Then we should change that also in this PR. It would be a generally small fix, I think.

**Comment by jimmikaelkael** [comment]
Yeah, the fix was quite easy.

**Comment by jimmikaelkael** [comment]
This is good to pull.
For my own information, are you using the github "Merge pull request" button when pulling ?

**Comment by TekkitCommando** [comment]
This is awesome maybe Glowstone++ will get as big as CraftBukkit :)

**Comment by mastercoms** [comment]
@jimmikaelkael Well, when the PR is perfect, I use the big green merge button. When I want to make changes and the PR is WIP, I pull it into the pull requesters repository. If the PR is 'finished' and I want to make changes, I pull it and modify it locally, and merge it using the command line.

**Comment by jimmikaelkael** [comment]
@mastercoms Thank you for the informations. I let you merge this one I prefer for the moment.

**Pull request merged**
