### PR TITLE
Use Class Sapling instead of Class Tree in Sapling

### PR DESCRIPTION
**Pull request by hibo98**

### CODE REVIEW

**Comment by mastercoms** [comment]
Thank you!

**Comment by jimmikaelkael** [comment]
I just don't understand why they added a Sapling api in bukkit if you can't get it's age. This sounds stupid as they had everything to add it...

It would have helped to get rid of those ordinal checks which is kind of dirty.

That said, nice addition!

**Comment by mastercoms** [comment]
@jimmikaelkael the person who added the sapling api is @hibo98.

**Comment by jimmikaelkael** [comment]
Ah, this is forgivable then. Sorry for the rude words.

**Pull request merged**
