### PR TITLE
Bluekelp refactors the world

### PR DESCRIPTION
**Pull request by bluekelp**
GlowWorld cleanups

should be (!!) almost no functional change. made a micro-optimization in the "all players asleep" detection but otherwise I believe it to be functionally 100% as before.

### CODE REVIEW

**Comment by mastercoms** [comment]
Ready for review?

**Comment by bluekelp** [comment]
yes. not sure what the process is - thought opening the PR meant that. I don't have the ability to edit labels on this PR - should I add a label in the future when creating it to indicate if it's ready?

**Comment by mastercoms** [comment]
The proper way is to put WIP for work in progress in your title if it is not ready for reviw, but not everyone does that, unfortunately,  so I have to ask.

**Comment by bluekelp** [comment]
ah, that remember seeing the [WIP] mentioned. thanks for asking.

nope, ready to go. just some cleanups as I was poking around in prep for some experimental stuff that unfortunately didn't pan out.

**Comment by mastercoms** [comment]
Works for me. Thanks for your PR!

**Pull request merged**
