### PR TITLE
Add TheEnd dimension generation

### PR DESCRIPTION
**Pull request by jimmikaelkael**
#### Progress
- [x] implement the terrain generator
- [x] create the pillars objects
- [x] implement a pillars/crystals populator

**Related Links:**
Related issue: #124

### CODE REVIEW

**Comment by mastercoms** [comment]
Awesome!

**Comment by jimmikaelkael** [comment]
Thank you!

**Comment by jimmikaelkael** [comment]
@mastercoms  I think this is good to go.

**Comment by mastercoms** [comment]
This looks good, amazing world generation as always.

**Pull request merged**
