### PR TITLE
Support Itemflags

### PR DESCRIPTION
**Pull request by Paulomart**

### CODE REVIEW

**Comment by Paulomart** [comment]
@mastercoms OK with merge?

**Comment by mastercoms** [comment]
Sorry, I've been sick for the few days, and I would much rather read code with a clearer mind. I'm getting better, so perhaps tomorrow I'll look at all of these issues and PRs that are piling up.

**Comment by mastercoms** [comment]
We'll have to modify the give command to support tags later. https://github.com/GlowstonePlusPlus/Glowkit/blob/bukkit%2Bglowkit/src/main/java/org/bukkit/command/defaults/GiveCommand.java

**Comment by Paulomart** [comment]
Want me to add this?

**Comment by mastercoms** [comment]
If you're ok with it, but I'll merge after testing even if it's not included.

**Comment by Paulomart** [comment]
Sure, begin testing, I will see if I can add it tomorrow

**Comment by mastercoms** [comment]
Ok.

**Comment by Paulomart** [comment]
Thinking this is out of scope of this PR since g++ currently has no framework for supporting the /give command unsafes

**Comment by mastercoms** [comment]
Ok.

**Comment by mastercoms** [comment]
Doesn't work for HideFlags:2, attribute modifier.

**Comment by Paulomart** [comment]
The others work?

**Comment by mastercoms** [comment]
Yes, all of the others work.

**Comment by Paulomart** [comment]
@mastercoms `/give Paulomart minecraft:diamond_sword 1 0 {ItemFlags:2}` does not even work in Vanlilla for more

**Comment by mastercoms** [comment]
Should I merge this and have you fix the bug later? Because there aren't any bugs affecting stability, just a missing feature.

**Comment by Paulomart** [comment]
Okay, because I don't have any clue what's causing the issue..

**Pull request merged**
