### PR TITLE
Switch to machine executor rather than Docker

### PR DESCRIPTION
**Pull request by Pr0methean**
May be the only way to stop OOM kills while still using CircleCI and properly supporting JDK8.

Relevant: #866

### CODE REVIEW

**Comment by mastercoms** [comment]
Should `build-deploy` still be using docker?

**Comment by Pr0methean** [comment]
No, because `build-deploy` has also been flaking with OOM kills (and would probably do so more often as we continued to increase test coverage). That said, I'd be in favor of a secondary build that used JDK9, and that would probably *have* to run on Docker if it was on CircleCI at all (all of CircleCI's `machine` images seem to be using JDK8).

**Comment by mastercoms** [comment]
Then why is only `build` being switched from Docker to machine?

**Comment by Pr0methean** [comment]
Wasn't aware of that; should be fixed now.

**Pull request merged**
