### PR TITLE
More entities

### PR DESCRIPTION
**Pull request by twizmwazin**
I added most of the mobs that were missing, and implemented their storage. Not everything is perfect and villagers, for instance have much work yet to be done, but this is a start.

### CODE REVIEW

**Comment by mastercoms** [comment]
Is this ready for review?

**Comment by twizmwazin** [comment]
yes

**Comment by mastercoms** [comment]
The code looks good. I am going to test it now.

**Comment by twizmwazin** [comment]
Tiny little fix there

**Comment by mastercoms** [comment]
Thanks for this awesome contribution!

**Comment by mastercoms** [comment]
Oh and, per our contribution policy, I've added you to the org because of your notable contribution.

**Pull request merged**
