### PR TITLE
Implement PlayerSpawnLocationEvent

### PR DESCRIPTION
**Pull request by Paulomart**
Really hacky solution :(

### CODE REVIEW

**Comment by kamcio96** [comment]
I have some idea for it. Can I do it or do you want change something?

**Comment by Paulomart** [comment]
Sure, give it a try

**Comment by kamcio96** [comment]
@Paulomart https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/tree/event/locationspawn could you test it? Today i don't have enought time :/

**Comment by mastercoms** [comment]
Preferring this pull because it's good to be dirty (sometimes).

**Pull request merged**
