### PR TITLE
Change map with scoreboard entries

### PR DESCRIPTION
**Pull request by kamcio96**
I didn't test it. But should work :wink:

### CODE REVIEW

**Comment by mastercoms** [comment]
What if someone changes their name?

**Comment by kamcio96** [comment]
We don't care about it, addPlayer is deprecated :wink:

**Comment by mastercoms** [comment]
So if someone changes their name it will show their previous name? Is that not a bug?

**Comment by kamcio96** [comment]
idk, probably yes
Spigot has 2 string maps

**Comment by mastercoms** [comment]
Closing due to the aforementioned bug.

**Comment by mastercoms** [comment]
Merged, but git isn't detecting it :(. https://github.com/GlowstoneMC/Glowstone/commit/0069bce5c60c62a4ee2cc4f63ea4d43599c278f1

**Pull request closed without merging**
