### PR TITLE
Furnace

### PR DESCRIPTION
**Pull request by hibo98**
Implementation of furnace

TODO:
- [x] Furnace Recipes
- [x] Furnace Fuels
- [x] Tick furnace only when ready for burning
- [x] Implementation of FurnaceBurnEvent
- [x] Implementation of FurnaceSmeltEvent
- [x] Rewind 2x Speed when no Fuel

Should be done in an other PR:
- Implementation of FurnaceExtractEvent
  (I think with the current WindowClickHandler this isn't possible, because FurnaceExtractEvent is BlockXpEvent)
- Change Block on Burning

For this PR [Glowkit#11](https://github.com/GlowstonePlusPlus/Glowkit/pull/11) and [Glowkit#13](https://github.com/GlowstonePlusPlus/Glowkit/pull/13) is needed

### CODE REVIEW

**Comment by mastercoms** [comment]
Please rebase on top of master or pull from Glowkit so that you get the merged changes from Glowkit.

**Comment by hibo98** [comment]
I've rebased, and I think it is better if you update Glowkit commit in GlowstonePlusPlus

**Comment by mastercoms** [comment]
Oh, hm, I thought I had updated Glowkit on master, sorry about that mistake!

**Comment by mastercoms** [comment]
Thank you for your contribution!

**Pull request merged**
