### PR TITLE
1.12.2 Update

### PR DESCRIPTION
**Pull request by aramperes**
1.12.2 Protocol and API update for Glowstone.

This should only be merged after `2017.9` is released, as it will be the last release to support 1.12.1.

### CODE REVIEW

**Comment by mastercoms** [comment]
Should I not just make the tag for 2017.9 now? I'd rather have this on master ASAP.

**Comment by aramperes** [comment]
Since it's the end of the month anyways, you can release 2017.9 as the last release with 1.12.1 support, and then merge this to begin the 2017.10 cycle.

**Comment by mastercoms** [comment]
Thank you, Momo. Really appreciate all of your work for the project :).

**Comment by aramperes** [comment]
Thank you 😊

**Pull request merged**
