### PR TITLE
Fix containers not dropping contents in creative.

### LINKED ISSUE #328: Destroying an inventory-holding block in creative doesn't drop contents.
When in creative mode, destroying a inventory block such as chests, hoppers, droppers and dispensers will not drop the contents of the inventory on the ground.

Note that this does not occur in survival mode (works as intended).

### PR DESCRIPTION
**Pull request by aramperes**
Fixes #328.

No extra information needed.

### CODE REVIEW

**Comment by mastercoms** [comment]
please always use braces :)

**Comment by aramperes** [comment]
Could've use a ternary there instead. Don't blame me for making it clearer than it could've been ;)

**Comment by mastercoms** [comment]
oh yes use ternary it is much more clear

**Comment by aramperes** [comment]
you dropped this: /s

**Pull request merged**
