### PR TITLE
Fix BlockFire freezing the server

### LINKED ISSUE #209: Nether hangs
It wasn't happening until recently, but now as soon as I teleport to the nether the server hangs...
I get kicked after a while for 'time out' reason and the server is frozen.

I've noticed too that I'm often kicked for hacking reason at first connection attempt. 

Sometimes I enter infinite loops where I start a server with fresh worlds, I get spawned in the air then fall and die. I'm sent back to another location then I'm kicked for hacking reason, I reconnect and the loop start over again.

Server log:
http://pastebin.com/ys8Gu2sD

Note (tests regarding nether freeze bug):
Not happening with 05caa512b992e62314b46a66f2d9c87e0d697d89
Hapening with e0646d22080f8a0293a80a8efc67ce762a612b0f
Hapening with c42b204e4c4e17fde833837acc5a5d7a1ee0c7e5 (for reference as above faulty commit name appear in commit message)

### PR DESCRIPTION
**Pull request by jimmikaelkael**
Fixes #209.

### CODE REVIEW

**Comment by kamcio96** [comment]
```hasRequestedPulse``` is shared by all blocks. So I'm not sure it works.

**Comment by jimmikaelkael** [comment]
Slap in my face, it's not required anyway.

**Comment by kamcio96** [comment]
close?

**Comment by jimmikaelkael** [comment]
Close what ?

**Comment by mastercoms** [comment]
Is this the problem with nether crashing?

**Comment by mastercoms** [comment]
Thanks for this fix.

**Pull request merged**
